### ISSUE TITLE
how can I use.. :(

### ISSUE THREAD

**Issue by davut5** [rishi-raj-jain/twitterUsernamefromUserID#10]
pip3 install twitterUsernameviaUserID it's installed. but how can I use. i don't understand.

**Comment by rishi-raj-jain** [comment]
the package is made for extracting the user profile handles if you have their ids. So just curate a list of twitter profile ids and then 
`
from twitterUsernameviaUserID import getHandles as gH
temp= gH.getHandles([<list of user ids>], 5)
`
and then temp will contain the dictionary with the handles if for an id.

**Comment by davut5** [comment]
i have 1 user..  I create  get.py and copy 

from twitterUsernameviaUserID import getHandles as gH
temp= gH.getHandles(id, 5)

run terminal   python3 get.py   give me error..

**Comment by rishi-raj-jain** [comment]
What's the error that you receive?

**Comment by davut5** [comment]
python3 get.py
,  File "getir.py", line 3
    temp= gH.getHandles(2871102189, 5)
IndentationError: unexpected indent

**Comment by davut5** [comment]
python3 get.py
,  File "/Users/...../Desktop/get.py", line 3
    temp= gH.getHandles(1111111111, 5)
IndentationError: unexpected indent

**Comment by davut5** [comment]
ModuleNotFoundError: No module named 'numpy'

**Comment by rishi-raj-jain** [comment]
I would be happy if you read the instructions again!
As of now, if you receive numpy error just install it via pip.

**Comment by davut5** [comment]
oh works now.. :) thanks.

**Comment by davut5** [comment]
No usernames provided

**Comment by davut5** [comment]
temp= gH.getHandles(234234234, 5) like that
or
temp= gH.getHandles([234234234], 5)  
or which format
temp= gH.getHandles(?, 5)

**Comment by rishi-raj-jain** [comment]
aah that must be because of the way provided, umm I'll add this to documentation. Just use ["1234454444"] instead of passing the number to the array.

**Comment by rishi-raj-jain** [comment]
Updated in the documentation
