### ISSUE TITLE
Question: Selenium reliance?

### ISSUE THREAD

**Issue by BrandonKMLee** [rishi-raj-jain/twitterUsernamefromUserID#11]
As observed in https://github.com/warproxxx/Twitter-Account-ID-to-Username-Converter/blob/master/tweet_scraper/tweet.py
It seemed that Selenium is not required, is that true?

**Comment by rishi-raj-jain** [comment]
As far as I could see, the project is fetching the user & tweet details from a particular status, which in turn requires you to have the tweet id. While the problem I'm tackling here is to say you've 50K user ids (only) and need the twitter handle from them (for let's say some identity resolution task)... in that case you can use this package.

**Comment by BrandonKMLee** [comment]
From a pure ID-to-username standpoint, would Selenium be excessive?

**Comment by rishi-raj-jain** [comment]
Nah, given that you can do threading (as done in the package), Selenium would not be excessive.

**Comment by BrandonKMLee** [comment]
Sorry for the call-out bro but it seems https://github.com/Altimis/Scweet/issues/54 is missing something, hope you can collab on this
