### ISSUE TITLE
Threading to improve speed?

### ISSUE THREAD

**Issue by rishi-raj-jain** [rishi-raj-jain/twitterUsernamefromUserID#5]
Currently, this allows 50K users in a span of 69 hours, while even with three instances in parallel, this could drastically reduce to 23 hours and the user won't need to do anything. It'd be better than APIs as you don't have to wait for say another day to start hitting APIs. Any ideas @DVanne ?

**Comment by DVanne** [comment]
@rishi-raj-jain definitely agree about the advantages over API. Would be good to develop in the direction of having multiple instances, great idea I think. Looks like it is possible to run parallel instances with Selenium.
